module.exports = {
	user: "user",
	province: "province",
	address: "address",
	planting: "planting",
	consumer: "consumer",
	producer: "producer",
	product: "product",
	category: "category",
	purchase: "purchase",
	cart_item: "cart_item",
	purchase_products: "purchase_products",
	purchase_location: "purchase_location",
	subscriber: "subscriber",
	api: "api",
};
